# -*- coding: utf-8 -*-

number_map = {
    "0": "zero",
    "1": "um",
    "2": "dois",
    "3": "três",
    "4": "quatro",
    "5": "cinco",
    "6": "seis",
    "7": "sete",
    "8": "oito",
    "9": "nove",
    "10": "dez",
    "11": "onze",
    "12": "doze",
    "13": "treze",
    "14": "quatorze",
    "15": "quinze",
    "16": "dezesseis",
    "17": "dezessete",
    "18": "dezoito",
    "19": "dezenove",
    "20": "vinte",
    "30": "trinta",
    "40": "quarenta",
    "50": "cinquenta",
    "60": "sessenta",
    "70": "setenta",
    "80": "oitenta",
    "90": "noventa",
    "100": "cem",
    "100s": "cento",
    "200": "duzentos", 
    "300": "trezentos", 
    "400": "quatrocentos", 
    "500": "quinhentos", 
    "600": "seiscentos", 
    "700": "setecentos", 
    "800": "oitocentos", 
    "900": "novecentos", 
    "1e3": "mil",
    "1e3s": "mil",
    "1e6": "milhão",
    "1e6s": "milhões",
    "1e9": "bilhão",
    "1e9s": "bilhões",
    "1e12": "trilhão",
    "1e12s": "trilhões",
    "1e15": "quadrilhão",
    "1e15s": "quadrilhões",
    "1e18": "quintilhão",
    "1e18s": "quintilhões",
    "1e21": "sextilhão",
    "1e21s": "sextilhões",
    "1e24": "septilhão",
    "1e24s": "septilhões"
}

reverse_number_map = {
    'zero': 0,
    'um': 1,
    'hum': 1,
    'dois': 2,
    'três': 3,
    'tres': 3,
    'quatro': 4,
    'cinco': 5,
    'seis': 6,
    'sete': 7,
    'oito': 8,
    'nove': 9,
    'dez': 10,
    'onze': 11,
    'doze': 12,
    'treze': 13,
    'catorze': 14,
    'quatorze': 14,
    'quinze': 15,
    'dezesseis': 16,
    'dezessete': 17,
    'dezoito': 18,
    'dezenove': 19,
    'vinte': 20,
    'trinta': 30,
    'quarenta': 40,
    'cinquenta': 50,
    'sessenta': 60,
    'setenta': 70,
    'oitenta': 80,
    'noventa': 90,
    'cem': 100,
    'cento':100,
    'duzentos':200,
    'trezentos':300,
    'quatrocentos':400,
    'quinhentos':500,
    'seiscentos':600,
    'setecentos':700,
    'oitocentos':800,
    'novecentos':900
    }

thousands_map = {
    'mil': 1000,
    'mil,': 1000,
    'milhão': 1000000,
    'milhao': 1000000,
    'milhões': 1000000,
    'milhoes': 1000000,
    'bilhão': 1000000000,
    'bilhao': 1000000000,
    'bilhões': 1000000000,
    'bilhoes': 1000000000
    }


currency_pt = ["um","dois","três","quatro","cinco","seis","sete","oito","nove",
                "dez","onze","doze","treze","quatorze","quinze","dezesseis","dezessete","dezoito","dezenove",
                "vinte","trinta","quarenta","cinquenta","sessenta","setenta","oitenta","noventa","cem",
                "cento","duzentos","trezentos","quatrocentos","quinhentos","seiscentos","setecentos","oitocentos","novecentos",
                "mil","milhão","bilhão","trilhão","quatrilhão","milhões","bilhões","trilhões","quatrilhões", 
                "e", "real", "reais", "centavo", "centavos"]